language: node_js
node_js:
- 4.2.2
deploy:
  provider: heroku
  api_key:
    secure: TV8nx6EEB+di2poOEuIcDhNUe0Vtsm3cu18KHhmveoilQNqcN6s3xCGq0OdFNhG0Mv2sVaqDWGHiljXfYZLI74qy1qVTPkJWcjvJqMFnOPqeyE/5cWH0degbIsFUPL59R+fK8n57hLckSAAE3R9OLE515u6wt9ezh8jSrxxyEhaBv+IkVt9xYPBIx5pUVBeS+g/HypTO8MHtBKuA6BOycrb7m0Fn87tG0OZRLorvMn9Rk667nxnbbUfujrJXa/Q9g41swuH0tpeiYr/yrmmjmRNLuMsEtqwjPG1o+eIwR5vl1zk2ynBpi/8yIpSQgD6N905KeGv3iJph1DGYq3XC0KFt1DC1O9IFCExqA1/tap7iCcluTk/en71D5AlEVpsEFRGCm6dY+/xWLzIor74FO/a4ytGTECTENMJYbd2h3onFf6zBRsI6xPATcE7+bhErIllndqxSx5KgiiZ+tHU/qMyGOr048pZLhw20rYHXUc8fFeDnxK0XpL2FTVZSTP7MHFrCidq0fK8nPfnTAI20Xw0UIhNth5Z68+Z7ESUi0+BDFZwbMT+JMnkqZo3XsoC8leTYr5aIz1SGHchWvU/S24rbFsoOuYzacYCD5+FVJ50fLP5gWxxI6M8nbhZE7Qw63VTpZ8AQkbdTsUbaNFkIdL+n/oh3VaRLU8UMLBfleaI=
